package com.iaven.mapper;


import com.iaven.pojo.table.Bill;
import com.iaven.pojo.table.BillExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface BillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    int countByExample(BillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    int deleteByExample(BillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    int insert(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    int insertSelective(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    List<Bill> selectByExample(BillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    int updateByExampleSelective(@Param("record") Bill record, @Param("example") BillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    int updateByExample(@Param("record") Bill record, @Param("example") BillExample example);
}