package com.yufop.tran.pojo.table;

public class Bill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.billid
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    private Integer billid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.goodname
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    private String goodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.amount
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.store
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    private String store;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.receivername
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    private String receivername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.receiveadd
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    private String receiveadd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.sendadd
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    private String sendadd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.tel
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.transunitid
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    private Integer transunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.transunitname
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    private String transunitname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.billid
     *
     * @return the value of bill.billid
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public Integer getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.billid
     *
     * @param billid the value for bill.billid
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public void setBillid(Integer billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.goodname
     *
     * @return the value of bill.goodname
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public String getGoodname() {
        return goodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.goodname
     *
     * @param goodname the value for bill.goodname
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public void setGoodname(String goodname) {
        this.goodname = goodname == null ? null : goodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.amount
     *
     * @return the value of bill.amount
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.amount
     *
     * @param amount the value for bill.amount
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.store
     *
     * @return the value of bill.store
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public String getStore() {
        return store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.store
     *
     * @param store the value for bill.store
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public void setStore(String store) {
        this.store = store == null ? null : store.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.receivername
     *
     * @return the value of bill.receivername
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public String getReceivername() {
        return receivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.receivername
     *
     * @param receivername the value for bill.receivername
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public void setReceivername(String receivername) {
        this.receivername = receivername == null ? null : receivername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.receiveadd
     *
     * @return the value of bill.receiveadd
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public String getReceiveadd() {
        return receiveadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.receiveadd
     *
     * @param receiveadd the value for bill.receiveadd
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public void setReceiveadd(String receiveadd) {
        this.receiveadd = receiveadd == null ? null : receiveadd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.sendadd
     *
     * @return the value of bill.sendadd
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public String getSendadd() {
        return sendadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.sendadd
     *
     * @param sendadd the value for bill.sendadd
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public void setSendadd(String sendadd) {
        this.sendadd = sendadd == null ? null : sendadd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.tel
     *
     * @return the value of bill.tel
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.tel
     *
     * @param tel the value for bill.tel
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.transunitid
     *
     * @return the value of bill.transunitid
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public Integer getTransunitid() {
        return transunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.transunitid
     *
     * @param transunitid the value for bill.transunitid
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public void setTransunitid(Integer transunitid) {
        this.transunitid = transunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.transunitname
     *
     * @return the value of bill.transunitname
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public String getTransunitname() {
        return transunitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.transunitname
     *
     * @param transunitname the value for bill.transunitname
     *
     * @mbggenerated Tue Jun 13 21:38:13 CST 2023
     */
    public void setTransunitname(String transunitname) {
        this.transunitname = transunitname == null ? null : transunitname.trim();
    }
}